# Generated by Django 6.0 on 2025-12-18 04:50

import apps.ticket.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_remove_admin_is_active_admin_is_blocked_and_more'),
        ('ticket', '0001_initial'),
        ('user', '0002_remove_user_is_active_user_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_from_admin',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='custom_admin.admin'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='user.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting_admin', 'Waiting Admin'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default=apps.ticket.models.generate_ticket_number, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('replied', 'Replied'), ('closed', 'Closed'), ('transferred', 'Transferred')], max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.admin')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
