# Generated by Django 6.0 on 2025-12-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_message_file_id_remove_message_is_from_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.CharField(blank=True, help_text='Telegram file_id', max_length=255, null=True),
        ),
    ]
