# Generated by Django 6.0 on 2025-12-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting_admin', 'Waiting Admin'), ('waiting_user', 'Waiting User'), ('in_progress', 'In Progress'), ('replied', 'Replied'), ('escalated', 'Escalated'), ('expired', 'Expired'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
