# Generated by Django 6.0 on 2025-12-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_remove_admin_is_active_admin_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='Translation needed', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='Требуется перевод', max_length=100, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default='Tarjima kerak', max_length=100, verbose_name='Name (Uzbek)'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
