# Generated by Django 6.0 on 2025-12-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_category_options_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
